refactor: Downgrade apispec to v4.4.1
The previous version 5.1.1 was causing a persistent AttributeError: 'Integer' object has no attribute 'load_default'